#!/usr/bin/env python3
"""Generate src/engine/blitq_types.h from the blit-queue handlers.

The queue's record format is defined by the interrupt handlers that read
it and nowhere else, so the table is EXTRACTED rather than transcribed:
every `move.l/(w) (A5)+,($xx,A6)` in a type's handler becomes one field,
in order.  Re-run it if the decode image changes.

  python3 tools/blitq_types.py > src/engine/blitq_types.h
"""
import subprocess, re, sys

DISPATCH = 0x21718a
TYPES = {1: 0x2171f2, 2: 0x217222, 3: 0x2172ba, 4: 0x217356, 5: 0x2173f6,
         6: 0x217496, 7: 0x217518, 0xa: 0x2175b2, 0xb: 0x217664,
         0xc: 0x217716}
END = 0x2177d0

def main():
    out = subprocess.run(['./build/dasm', 're/pipeline/decode.bin',
                          hex(DISPATCH), hex(END)],
                         capture_output=True, text=True).stdout.splitlines()
    at = {}
    for line in out:
        m = re.match(r'\$(\w+)\s+(.*)', line)
        if m:
            at[int(m.group(1), 16)] = m.group(2)

    print("/* GENERATED by tools/blitq_types.py -- do not edit.")
    print(" *")
    print(" * One row per field of each blit-queue record type, read off the")
    print(" * interrupt handlers that consume them (see re/BLITQUEUE.md).")
    print(" * `wide` is 1 for a long, 0 for a word; `reg` is the custom")
    print(" * register offset it is written to. */")
    print("#ifndef LOTUS2_BLITQ_TYPES_H")
    print("#define LOTUS2_BLITQ_TYPES_H")
    print("")
    print("/* src: 0 = the constant in `value`, 1 = taken off the queue.")
    print(" * wide: 1 if the handler writes a LONG (two registers), 0 for a")
    print(" * word -- it matters for both, because move.l #x,($40,A6) sets")
    print(" * BLTCON0 and BLTCON1 while move.w sets only BLTCON0. */")
    print("typedef struct { unsigned char src, wide, reg; unsigned int value; }")
    print("        BlitqField;")
    print("typedef struct { unsigned char type, count;")
    print("                 const BlitqField *field; } BlitqType;")
    print("")
    tables = []
    def blitter_reg(r):
        """Only the blitter's own registers.  The handlers also poke
        INTREQ ($9c) and the copper, which have nothing to do with the
        record's contents."""
        return 0x40 <= r <= 0x76

    for t in sorted(TYPES):
        start = TYPES[t]
        later = sorted(a for a in TYPES.values() if a > start)
        stop = later[0] if later else END
        fields = []
        for a in sorted(at):
            if not (start <= a < stop):
                continue
            txt = at[a]
            m = re.match(r'move\.(l|w)\s+\(A5\)\+, \(\$(\w+),A6\)', txt)
            if m:
                r = int(m.group(2), 16)
                if blitter_reg(r):
                    fields.append((1, 1 if m.group(1) == 'l' else 0, r, 0))
                continue
            m = re.match(r'move\.(l|w)\s+#\$(\w+), \(\$(\w+),A6\)', txt)
            if m:
                r = int(m.group(3), 16)
                if blitter_reg(r):
                    fields.append((0, 1 if m.group(1) == 'l' else 0, r,
                                   int(m.group(2), 16)))
                continue
            m = re.match(r'clr\.(l|w)\s+\(\$(\w+),A6\)', txt)
            if m:
                r = int(m.group(2), 16)
                if blitter_reg(r):
                    fields.append((0, 1 if m.group(1) == 'l' else 0, r, 0))
        if not fields:
            continue
        name = "blitq_t%x" % t
        tables.append((t, name, len(fields)))
        qbytes = sum(4 if f[1] else 2 for f in fields if f[0])
        print("/* type $%x: handler $%06x, %d bytes off the queue */" %
              (t, start, qbytes))
        print("static const BlitqField %s[] = {" % name)
        for src, wide, reg, val in fields:
            print("    { %d, %d, 0x%02x, 0x%x }," % (src, wide, reg, val))
        print("};")
    print("")
    print("static const BlitqType blitq_types[] = {")
    for t, name, n in tables:
        print("    { 0x%02x, %d, %s }," % (t, n, name))
    print("};")
    print("#define BLITQ_TYPE_COUNT %d" % len(tables))
    print("")
    print("#endif")

main()
